services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    port: 10000
    
    envVars:
      # Database
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromEnvVar: NEON_HOST
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        fromEnvVar: NEON_DB_NAME
      - key: DB_POSTGRESDB_USER
        fromEnvVar: NEON_USER
      - key: DB_POSTGRESDB_PASSWORD
        fromEnvVar: NEON_PASSWORD
      - key: DB_POSTGRESDB_SSL
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      
      # App
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-on-render-kb7j.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Jakarta
